# Generated by Django 4.1.6 on 2023-03-03 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Quesiton",
            new_name="Question",
        ),
    ]
